### ISSUE TITLE
Impossibility of comparing dates if one of the dates is null

### ISSUE THREAD

**Issue by sblrok** [Dr-klo/audit-diff#2]
Hello! Сould you help me with the some error?
I get an error when I try to compare two objects, one of which has a date that is null

![image](https://user-images.githubusercontent.com/9702472/60964564-27d4d600-a303-11e9-96e9-97744f840e4e.png)
I tried to log dates: 
```
// line 161, file diff.service.js
if (newval instanceof Date || oldval instanceof Date) {
    console.log(newval, typeof newval, new Date(newval), oldval, typeof oldval, new Date(oldval));
    if (new Date(newval).toISOString() !== new Date(oldval).toISOString()) {
        return new diff_details_1.DiffDetails(currentPath, path, new Date(oldval).toLocaleString(), new Date(newval).toLocaleString());
    }
}
```
![image](https://user-images.githubusercontent.com/9702472/60964816-da0c9d80-a303-11e9-82a2-2dd5083a17a7.png)

**Comment by Dr-klo** [comment]
Fixed it in version 1.0.9. Thanks for bug report.
